spring:
  application:
    name: mrp-system
  datasource:
    url: jdbc:mysql://localhost:3306/sparkit_mrp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true

rocketmq:
  name-server: localhost:9876
  producer:
    group: mrp-producer-group
    send-message-timeout: 3000

server:
  port: 8080

springdoc:
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    path: /api/v1/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
